# Generated by Django 4.2 on 2023-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_domicilio_persona_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
