# Generated by Django 4.2 on 2023-05-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='hora',
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_y_hora',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
