# Generated by Django 4.2 on 2023-05-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_persona_fecha_y_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_y_hora',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
