# Generated by Django 4.2 on 2023-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_medico_paciente_turno_turno_turno_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_y_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
