# Generated by Django 4.2 on 2023-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_remove_turno_turno_unico_turno_turno_ocupado_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='turno_ocupado',
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='paciente_fecha_hora_ocupada',
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='medico_fecha_hora_ocupada',
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('paciente', 'medico', 'fecha_y_hora'), name='turno_ocupado'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha_y_hora'), name='paciente_fecha_hora_ocupada'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_y_hora'), name='medico_fecha_hora_ocupada'),
        ),
    ]
