# Generated by Django 4.2 on 2023-05-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_remove_turno_turno_ocupado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='domicilio',
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.paciente'),
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
