# Generated by Django 4.2 on 2023-06-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0018_remove_persona_domicilio_alter_turno_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
