# Generated by Django 4.2 on 2023-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0019_alter_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
